class Catalonia
  library = [
    'Catalonia comprises four provinces: Barcelona, Girona, Lleida, and Tarragona. The capital and largest city is Barcelona, the second largest city in Spain, and the centre of one of the largest metropolitan areas in Europe, and it comprises most of the territory of the former Principality of Catalonia, with the remainder now part of France.',
    'Catalonia is bordered by France and Andorra to the north, the Mediterranean Sea to the east, and the Spanish regions of Aragon and the Valencian Community to west and south respectively.',
    'In the 10th century the eastern counties of the March of Gothia and the Marca Hispanica became independent from the Frankish kingdom, uniting as vassals of Barcelona.',
    "In 1137 Barcelona and Aragon formed the Crown of Aragon, and Catalonia became a maritime power and the main base for the Crown of Aragon's naval power and expansionism in the Mediterranean.",
    "During the Reapers' War (1640–52), Catalonia rebelled against the presence of Castillian army in its territory, becoming a republic under French protection. Under the terms of the Treaty of the Pyrenees in 1659, which ended the wider Franco-Castillian war, Castille agreed with France to cede it the northern parts of Catalonia, mostly incorporated in the county of Roussillon.",
    'Despite the Napoleonic and Carlist Wars, Catalonia experienced economic growth and industrialisation. During the second half of the 19th century, the region saw a cultural renaissance coupled with incipient nationalism, while several workers movements appeared.',
    'In 1913, the four Catalan provinces formed a Commonwealth, and with the advent of democracy during the Second Spanish Republic (1931–39), the Generalitat of Catalonia, was restored. After the Spanish Civil War, the Francoist dictatorship enacted repressive measures, abolishing Catalan institutions and banning the official use of the Catalan language again.',
    "In 987, Wilfred the Hairy, count of Barcelona did not recognise Hugh Capet, making his successors (Sunyer, Borrell II, Miro I, and so on) de facto independent of the Carolingian crown. In 1137, Ramon Berenguer IV, Count of Barcelona decided to accept King Ramiro II of Aragon's proposal to marry Queen Petronila, establishing the dynastic union of the County of Barcelona with the Kingdom of Aragon, creating the Crown of Aragon and making the Catalan counties that were united under the county of Barcelona into a principality of the Aragonese Crown.",
    "As a coastal territory of the Crown of Aragon, Catalonia, Barcelona in particular, became the base of the Crown maritime dominion and lead the expansion, the power and the influence of the Crown of Aragon in the Mediterranean. Gradually, new territories such as, the Kingdom of Valencia, the Kingdom of Majorca and later Sardinia, the Kingdom of Sicily, Corsica and Duchy of Athens were incorporated under the dynasty of the House of Aragon and Barcelona (1164–1410) into the Crown. In the 12th century, under the patronage of the counts of Barcelona, a Catalan literature first appeared and flourished in the next few centuries.",
    "In 1410, King Martin I died without surviving descendants. As a result, by the Pact of Caspe, Ferdinand of Antequera from the Castilian dynasty of Trastámara received the Crown of Aragon as Ferdinand I of Aragon. His grandson, King Ferdinand II of Aragon, and Queen Isabella I of Castile married in 1469, becoming the Catholic Monarchs; subsequently, this event was seen by some Castilian historiographers as the dawn of the unified Kingdom of Spain. At that point, though united by marriage, the Crowns of Castile and Aragon maintained distinct territories, each keeping its own traditional institutions, parliaments and laws. Castile commissioned in monopoly the expeditions to the Americas, and benefited from the colonial riches. Political power gradually shifted away from the Aragonese court to the court of the Spanish Crown.",
    "The defeat of the Republic of Spain in the Spanish Civil War brought fascist Francisco Franco to power as dictator. His regime imposed linguistic, political and cultural restrictions across Spain. In Catalonia, any kind of public activities associated with Catalan nationalism, Anarchism, Socialism, Democracy or Communism, including the publication of books on those subjects or simply discussion of them in open meetings, was banned. Franco's regime banned the use of Catalan in government-run institutions and during public events. The pro-Republic of Spain President of Catalonia, Lluís Companys, was taken to Spain from his exile in the German-occupied France, tortured and executed for the crime of 'military rebellion'"
  ];

  def sample
    library.sample
  end
end
